### ISSUE TITLE
instantaneous (iv) parameter selection fetches daily value data (dv)

### ISSUE THREAD

**Issue by 7yl4r** [NatelEnergy/natel-usgs-datasource#1]
When using a "parameter" selection (checkboxes at bottom of screenshot below) for "instantaneous" service, the graph appears empty.

![image](https://user-images.githubusercontent.com/1051390/38825461-29d7a294-419c-11e8-9ae2-3561f0cd3798.png)

The underlying query when making this selection is sent to the `dv` (daily value) API endpoint, indicating that the uri is being improperly constructed for iv service requests. 

![image](https://user-images.githubusercontent.com/1051390/38826267-c7658e3e-419e-11e8-8e2f-6c1dcb6792e9.png)

I guess then the `dv` data is parsed using the `iv` data parser, resulting in no data because the column name format is different.

I am not familiar with grafana driver code, but maybe [this line](https://github.com/NatelEnergy/natel-usgs-datasource/blob/master/src/datasource.ts#L126) should be `target.args.service`?

**Comment by ryantxu** [comment]
Ahh -- it was switching to the daily values automatically when the requested interval was large.  In v0.0.2 I made that configurable:

![image](https://user-images.githubusercontent.com/705951/45530241-89d5b500-b79e-11e8-962d-3174d21cb569.png)

thanks for the feedback -- sorry I did not see this until just now :(

**Comment by 7yl4r** [comment]
No worries. Thanks for your work on this issue and the plugin itself! It has saved me quite a bit of work.
